### PR TITLE
fix: add disableTestsConsoleOutput option

### PR DESCRIPTION
**Pull request by ferrarafer**
Added option on `StackedLogger` to disable `ConsoleOutput` during tests.

### CODE REVIEW

**Review by FilledStacks — APPROVED** [review]
Is this ready to be merged?

**Comment by ferrarafer** [comment]
@FilledStacks probably 😄 , I will review today or during the weekend and we can merge.

**Comment by FilledStacks** [comment]
Awesome!

**Review by FilledStacks — APPROVED** [review]
LGTM

**Pull request merged**
