### PR TITLE
chore(deps): upgrade logger to 2.0.1

### PR DESCRIPTION
**Pull request by sebastianbuechler**
Updated `logger` package to version 2.0.1 and adjusted code in generator and unit tests. 

Most critical changes: According to https://pub.dev/packages/logger/changelog the `init` , `destroy` and `close` method are now async.

Closes #15.

### CODE REVIEW

**Comment by sebastianbuechler** [comment]
@ferrarafer can you please have a look at this one?

**Comment by sebastianbuechler** [comment]
@ferrarafer & @FilledStacks any news for this one?

**Comment by sebastianbuechler** [comment]
@FilledStacks & @ferrarafer is there a reason why not to upgrade to logger v2?

**Comment by ferrarafer** [comment]
@sebastianbuechler I think the logger package upgrade could break the package because we already did it and something went wrong. I will take a look as soon as possible.

**Comment by FilledStacks** [comment]
This would be a breaking change for the framework, we'll have to see how we can do it without causing a break first. 

If we can't we need to have the documentation ready to migrate over.

**Comment by sebastianbuechler** [comment]
@ferrarafer Any news on this? It seems to be blocking some other upgrades and increasing.

**Comment by FilledStacks** [comment]
@sebastianbuechler we'll release this on a beta branch as it's a breaking change. 

Sorry for the delay.

**Pull request merged**
