### PR TITLE
change: throw an exception when the dependency type is not implemented

### PR DESCRIPTION
**Pull request by eb-so**
Throw an exception when the dependency type is not implemented yet instead of using FactoryWithParam as a backup type to prevent future issues(like [this](https://github.com/Stacked-Org/stacked/issues/984)) when adding a new dependency type.

### CODE REVIEW

**Review by ferrarafer — DISMISSED** [review]
Good catch ❤️

**Comment by eb-so** [comment]
Fixed some tests too, I think the CI is passing now

**Comment by ferrarafer** [comment]
@eb-so I think coverage needs an argument, probably the output folder. Can you fix that? Will merge after the fix.

**Comment by eb-so** [comment]
@ferrarafer  Done

**Comment by eb-so** [comment]
@ferrarafer This is the command output on my machine
Screenshot 2023-07-17 at 11 30 52 PM

**Comment by eb-so** [comment]
@ferrarafer or we can use [this](https://github.com/marketplace/actions/very-good-coverage)

**Comment by ferrarafer** [comment]
> @ferrarafer or we can use [this](https://github.com/marketplace/actions/very-good-coverage)

If you wanna configure it, I have no problem. Otherwise, we can just replace the following line for now.

```bash
- run: dart run test --coverage ./coverage
```

with

```bash
- run: flutter test --coverage
```

**Comment by eb-so** [comment]
@ferrarafer I don't think that's the issue but I'll try

**Pull request merged**
